Navigation
joaopab1337/youtube-clone pull request #1
Opened 2019-08-12 22:15 UTC by joaopab1337

All the features related to the project are in this branch.

Ps.: We should have chosen a more descriptive name.

2019-08-13 00:48 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-13 14:08 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-13 14:33 UTC, Torres-ssf requested changes
### Great work team :clap: 
Nice job building your very first project :smile:
You folks get almost everything right, we just need to do a few changes to make your project even better. 

- [x] It's very important to have a descriptive readme file. This is the first thing that people look in your repository. Don't forget that in the future, your repositories are going to be part of your portfolio. If you need a direction on this you can make something like this one https://github.com/bolah2009/newsweek-clone/blob/master/README.md. The images are optional, but it's best practice have the name and git account of all contributors.

- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

- [x]  There is also one error in your CSS code. Check it using this CSS [validator](https://jigsaw.w3.org/css-validator/) . 

Please, kindly make these changes and submit for code review again. Happy coding :muscle: 

PS: I left some note in your code. They are all optional, but they will improve a lot the quality of your code.

2019-08-13 14:34 UTC, Torres-ssf commented on index.html
> +    <div class="navbar">
[OPTIONAL]
It's best practice to use the `nav` tag for the navbar. This makes your code more semantic and improves the overall quality of your code.

2019-08-13 14:34 UTC, Torres-ssf commented on index.html
> +    <div class="main">
[OPTIONAL]
It's best practice to use the `main` tag for the main content of your page. The main content of your page it's the most important part of it. In this project's case, the video section

2019-08-13 14:34 UTC, Torres-ssf commented on index.html
> +        <div class="section-sidebar">
[OPTIONAL]
It's also best practice to use the `aside` tag for the side section. All these 3 changes are related to best practices and semantic HTML(very important topic)

2019-08-14 02:17 UTC, Ispirett approved these changes
Hey @jstiven01 @joaopab1337  Great! job on your first project
![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

looks good to me you can merge and complete this project.
##### good luck on your next project.

2019-08-14 16:02 UTC, merged